POST http://localhost:5000/users/add 
Content-Type: application/json

{
    "username":"Priyanka"
}

###
http://localhost:5000/users



###
POST http://localhost:5000/post/add 
Content-Type: application/json

{
    "username":"640528e8581c197843d2dfdb",
    "heading": "How to ry MongoDB with like",
    "content": "I want to query something with SQL's like query:",
    "tags": ["sql","mongo-db","sql-like"]
}

###
POST http://localhost:5000/posts/add 
Content-Type: application/json

{
    "username":"640528e8581c197843d2dfdb",
    "heading": "How to search by text in Java on Mongo db",
    "content": "am using QueryBuilder at the moment, but it doesn't support that kind of query format.Any idea?",
    "tags": ["sql"]
}


###
http://localhost:5000/post

###
GET  http://localhost:5000/posts/64052d022b27aab1f0006f87 

###
DELETE http://localhost:5000/posts/64052dbf5feea039bcdea3b6

###
POST  http://localhost:5000/posts/update/64052d022b27aab1f0006f87 
Content-Type: application/json

{
    "username":"Meenakshi",
    "heading": "How to query MongoDB with like in SQL",
    "content": "I want to query something with SQL's like query:",
    "tags": ["sql","mongo-db","sql-like"]
}

###
GET http://localhost:5000/post/user/64319e5e56205a2666567676


###
GET http://localhost:5000/post/64333fb0b7c1b922a51be12b



###
GET http://localhost:5000/post

###
GET http://localhost:5000/comments/6433480b8805d84fca30595d

### 
PUT http://localhost:5000/comments/upvote/64342b0da1d9b9f2564d2840
Content-Type: application/json

{
    "user":"64319e5e56205a2666567676"
}

###
PUT http://localhost:5000/comments/downvote/64342b0da1d9b9f2564d2840
Content-Type: application/json

{
    "user":"64319e5e56205a2666567676"
}
###

POST http://localhost:5000/comments/upvoteclear/64342b0da1d9b9f2564d2840
Content-Type: application/json

{
    "user":"64319e5e56205a2666567676"
}
